'use client'
import './globals.css'

//session
import {SessionProvider} from "next-auth/react"

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children,session }) {
  return (
    <html lang="en">
      <SessionProvider session={session}>
      <body>{children}</body>
      </SessionProvider>
    </html>
  )
}
