"use client";
import "./globals.css";
import "react-toastify/dist/ReactToastify.css";

//session
import Providers from "@/components/Providers";
import NavBar from "@/components/NavBar";
import { ToastContainer } from "react-toastify";

//redux
import store from "@/store/reduxStore";

import { Provider } from "react-redux";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, session }) {
  return (
    <html lang="en">
      <body>

          <Providers>
        <Provider store={store}>
            <NavBar /> {children}
            <ToastContainer position="top-right" autoClose={3000} />
            </Provider>
          </Providers>
        
      </body>
    </html>
  );
}
